# Generated by Django 4.2.10 on 2025-09-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_now_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsla',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidentsla',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidenttask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicenowexecutionlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='syscompany',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sysuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tasktimeworked',
            options={'managed': False},
        ),
    ]
