# Generated by Django 4.2.10 on 2025-09-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_now_new', '0004_alter_incident_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False},
        ),
    ]
