# Generated by Django 4.2.10 on 2025-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17)),
                ('networkId', models.CharField(max_length=50)),
                ('productType', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('notes', models.TextField()),
                ('wan1Ip', models.GenericIPAddressField()),
                ('wan2Ip', models.GenericIPAddressField()),
                ('configurationUpdatedAt', models.DateTimeField()),
                ('firmware', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('tags', models.JSONField()),
                ('details', models.JSONField()),
            ],
            options={
                'verbose_name': 'Dispositivo Meraki',
                'verbose_name_plural': 'Dispositivos Meraki',
                'db_table': 'meraki_device',
            },
        ),
    ]
