# Generated by Django 4.2.10 on 2025-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lanIp',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='organization_id',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
