# Generated by Django 4.2.10 on 2025-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0002_device_lanip_device_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='configurationUpdatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lanIp',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='networkId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='productType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='wan1Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='wan2Ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
