# Generated by Django 4.2.10 on 2025-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0003_alter_device_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=50)),
                ('networkId', models.CharField(max_length=50, null=True)),
                ('productType', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('notes', models.TextField(null=True)),
                ('wan1Ip', models.GenericIPAddressField(null=True)),
                ('wan2Ip', models.GenericIPAddressField(null=True)),
                ('firmware', models.CharField(max_length=50, null=True)),
                ('organization_id', models.CharField(max_length=50)),
                ('lanIp', models.GenericIPAddressField(null=True)),
                ('sigla', models.CharField(max_length=50, null=True)),
                ('status_migrado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Inventário de Dispositivo Meraki',
                'verbose_name_plural': 'Inventário de Dispositivos Meraki',
                'db_table': 'meraki_device_inventario',
            },
        ),
    ]
