# Generated by Django 4.2.10 on 2025-07-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0004_deviceinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinventario',
            name='note_1',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='note_2',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='note_3',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
