# Generated by Django 4.2.10 on 2025-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0005_deviceinventario_note_1_deviceinventario_note_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinventario',
            name='note_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinventario',
            name='note_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinventario',
            name='note_3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
