# Generated by Django 4.2.10 on 2025-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0006_alter_deviceinventario_note_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinventario',
            name='notes',
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='note_4',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
