# Generated by Django 4.2.10 on 2025-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0007_remove_deviceinventario_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinventario',
            name='LP_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='LP_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='LP_3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='nome_operadora_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='nome_operadora_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='nome_operadora_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='tecnologia_1',
            field=models.CharField(choices=[('IP DEDICADO', 'IP DEDICADO'), ('BANDA LARGA', 'BANDA LARGA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='tecnologia_2',
            field=models.CharField(choices=[('IP DEDICADO', 'IP DEDICADO'), ('BANDA LARGA', 'BANDA LARGA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='tecnologia_3',
            field=models.CharField(choices=[('IP DEDICADO', 'IP DEDICADO'), ('BANDA LARGA', 'BANDA LARGA')], max_length=20, null=True),
        ),
    ]
