# Generated by Django 4.2.10 on 2025-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0008_deviceinventario_lp_1_deviceinventario_lp_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinventario',
            name='velocidade_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='velocidade_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='velocidade_3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
