# Generated by Django 4.2.10 on 2025-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0009_deviceinventario_velocidade_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinventario',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='endereco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deviceinventario',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
