# Generated by Django 4.2.10 on 2025-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCepNCidade',
            fields=[
                ('id_cidade', models.IntegerField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('cidade_sem_acento', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=2, null=True)),
                ('cidade_ibge', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=20, null=True)),
                ('ddd', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=2, null=True)),
                ('cidade_area', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_cep_n_cidade',
            },
        ),
    ]
