# Generated by Django 4.2.10 on 2025-06-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCepNBairro',
            fields=[
                ('id_bairro', models.IntegerField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('bairro_sem_acento', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('cidade_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=2, null=True)),
                ('latitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_cep_n_bairro',
            },
        ),
        migrations.CreateModel(
            name='TblCepNDistrito',
            fields=[
                ('id_distrito', models.IntegerField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('distrito_sem_acento', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('cidade_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=2, null=True)),
                ('latitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_cep_n_distrito',
            },
        ),
        migrations.CreateModel(
            name='TblCepNLogradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=8, null=True)),
                ('tipo', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('nome_logradouro', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=2, null=True)),
                ('tipo_sem_acento', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('nome_logradouro_sem_acento', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('logradouro_sem_acento', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=20, null=True)),
                ('cep_ativo', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=1, null=True)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correios.tblcepnbairro')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correios.tblcepncidade')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correios.tblcepndistrito')),
            ],
            options={
                'db_table': 'tbl_cep_n_logradouro',
            },
        ),
    ]
