# Generated by Django 4.2.10 on 2025-08-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0002_tblcepnbairro_tblcepndistrito_tblcepnlogradouro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcepnbairro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblcepncidade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblcepndistrito',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblcepnlogradouro',
            options={'managed': False},
        ),
    ]
