# Generated by Django 4.2.10 on 2025-07-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_now', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={'managed': False},
        ),
    ]
