# Generated by Django 4.2.10 on 2025-09-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_now', '0002_alter_backlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentsla',
            options={'managed': False},
        ),
    ]
