# Generated by Django 4.2.10 on 2025-06-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_now', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
    ]
