# Generated by Django 4.2.10 on 2025-07-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_now', '0002_alter_incident_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidentsla',
            options={'managed': False},
        ),
    ]
