from .d_assignment_group import DAssignmentGroup
from .d_company import DCompany
from .d_contract import DContract
from .d_incident_sla import DIncidentSla
from .d_operacao import DOperacao
from .d_premissa import DPremissa
from .d_resolved_by import DResolvedBy
from .d_resolved_by_assignment_group import DResolvedByAssignmentGroup
from .d_sorted_ticket import DSortedTicket
from .f_incident import FIncident
from .f_incident_bita import FIncidentsBita
from .f_incident_task import FIncidentTask
from .f_planta_vgr import FPlantaVgr
from .f_sae_localidades import FSaeLocalidades
