# Generated by Django 4.2.10 on 2025-05-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAssignmentGroup',
            fields=[
                ('id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
                ('dv_assignment_group', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'd_assignment_group',
            },
        ),
        migrations.CreateModel(
            name='DCompany',
            fields=[
                ('id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
                ('dv_company', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('u_cnpj', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=14, null=True)),
            ],
            options={
                'db_table': 'd_company',
            },
        ),
        migrations.CreateModel(
            name='DContract',
            fields=[
                ('id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
                ('dv_contract', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'd_contract',
            },
        ),
        migrations.CreateModel(
            name='DOperacao',
            fields=[
                ('id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
                ('dv_company', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('operacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'd_operacao',
            },
        ),
        migrations.CreateModel(
            name='DResolvedBy',
            fields=[
                ('id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
                ('dv_resolved_by', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=80)),
            ],
            options={
                'db_table': 'd_resolved_by',
            },
        ),
        migrations.CreateModel(
            name='DSortedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('mes_ano', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=7)),
            ],
            options={
                'db_table': 'd_sorted_ticket',
            },
        ),
        migrations.CreateModel(
            name='FIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('resolved_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('assignment_group', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('sla_atendimento', models.BooleanField(blank=True, null=True)),
                ('sla_resolucao', models.BooleanField(blank=True, null=True)),
                ('company', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_origem', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_u_categoria_da_falha', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_u_sub_categoria_da_falha', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_u_detalhe_sub_categoria_da_falha', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_state', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_id_vgr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_id_vantive', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_category', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_subcategory', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_u_detail_subcategory', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_tipo_indisponibilidade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('sys_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('resolved_at', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('scr_vendor_ticket', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_tipo_de_procedencia', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_sla_resolved', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dv_sla_first', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'f_incident',
            },
        ),
        migrations.CreateModel(
            name='FIncidentsBita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('assignment_group', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('resolved_at', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_origem', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('opened_at', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('opened_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('resolved_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('short_description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('dv_state', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('close_notes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'f_incidents_bita',
            },
        ),
        migrations.CreateModel(
            name='FIncidentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_operadora_integrador', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_outros', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_designa_o_lp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_protocolo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_data_in_cio', models.DateTimeField(blank=True, null=True)),
                ('u_data_fim', models.DateTimeField(blank=True, null=True)),
                ('u_tipo_acionamento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('u_produto', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'f_incident_task',
            },
        ),
        migrations.CreateModel(
            name='FPlantaVgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vantive', models.IntegerField(blank=True, db_column='ID_VANTIVE', null=True)),
                ('raiz_cod_cli', models.BigIntegerField(blank=True, db_column='RAIZ_COD_CLI', null=True)),
                ('cod_grupo', models.DecimalField(blank=True, db_column='COD_GRUPO', decimal_places=0, max_digits=18, null=True)),
                ('cliente', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='CLIENTE', max_length=300, null=True)),
                ('grupo_economico', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='GRUPO_ECONOMICO', max_length=350, null=True)),
                ('cnpj', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='CNPJ', max_length=30, null=True)),
                ('status_vantive', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='STATUS_VANTIVE', max_length=250, null=True)),
                ('servico', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='SERVICO', max_length=100, null=True)),
                ('endereco_completo', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='ENDERECO_COMPLETO', null=True)),
                ('cidade', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='CIDADE', max_length=100, null=True)),
                ('uf', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='UF', max_length=20, null=True)),
                ('cep', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='CEP', max_length=10, null=True)),
                ('regional', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='REGIONAL', max_length=100, null=True)),
                ('data_contrato', models.DateTimeField(blank=True, db_column='DATA_CONTRATO', null=True)),
                ('data_entrada', models.DateField(blank=True, db_column='DATA_ENTRADA', null=True)),
                ('data_rfs', models.DateField(blank=True, db_column='DATA_RFS', null=True)),
                ('data_rfb', models.DateField(blank=True, db_column='DATA_RFB', null=True)),
                ('data_rfb_nao_faturavel', models.DateTimeField(blank=True, db_column='DATA_RFB_NAO_FATURAVEL', null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, db_column='DATA_CANCELAMENTO', null=True)),
                ('isis_cancelamento_motivo', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='ISIS_CANCELAMENTO_MOTIVO', max_length=100, null=True)),
                ('justif_rfb', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='JUSTIF_RFB', max_length=50, null=True)),
                ('isis_motivo_pendencia', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='ISIS_MOTIVO_PENDENCIA', max_length=300, null=True)),
                ('combo', models.IntegerField(blank=True, db_column='COMBO', null=True)),
                ('caixa_unica', models.IntegerField(blank=True, db_column='CAIXA_UNICA', null=True)),
                ('revenda_vgr', models.IntegerField(blank=True, db_column='REVENDA_VGR', null=True)),
                ('modelo_atributos', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='MODELO_ATRIBUTOS', max_length=250, null=True)),
                ('projeto_especial', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='PROJETO_ESPECIAL', max_length=20, null=True)),
                ('delta_rec_liq', models.FloatField(blank=True, db_column='DELTA_REC_LIQ', null=True)),
            ],
            options={
                'db_table': 'f_planta_vgr',
            },
        ),
        migrations.CreateModel(
            name='FSaeLocalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vantive', models.IntegerField(blank=True, db_column='ID_VANTIVE', null=True)),
                ('uf', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='UF', max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='CIDADE', max_length=100, null=True)),
                ('data_rfb', models.DateField(blank=True, db_column='DATA_RFB', null=True)),
            ],
            options={
                'db_table': 'f_sae_localidades',
            },
        ),
        migrations.CreateModel(
            name='DResolvedByAssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_analytics.dassignmentgroup')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_analytics.dresolvedby')),
            ],
            options={
                'db_table': 'd_resolved_by_assignment_group',
            },
        ),
        migrations.CreateModel(
            name='DPremissas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_incidents', models.IntegerField()),
                ('is_contrato_lancado', models.BooleanField()),
                ('is_horas_lancadas', models.BooleanField()),
                ('is_has_met_first_response_target', models.BooleanField()),
                ('is_resolution_target', models.BooleanField()),
                ('is_atualizacao_logs_correto', models.BooleanField()),
                ('is_ticket_encerrado_corretamente', models.BooleanField()),
                ('is_descricao_troubleshooting', models.BooleanField()),
                ('is_cliente_notificado', models.BooleanField()),
                ('is_category_correto', models.BooleanField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_analytics.dassignmentgroup')),
            ],
            options={
                'db_table': 'd_premissas',
            },
        ),
    ]
