# Generated by Django 4.2.10 on 2025-05-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0003_alter_fincidentsbita_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fincidentsbita',
            name='updated_at',
        ),
    ]
