# Generated by Django 4.2.10 on 2025-05-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0004_remove_fincidentsbita_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fincidentsbita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
