# Generated by Django 4.2.10 on 2025-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0005_alter_fincidentsbita_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fincidentsbita',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fincidentsbita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
