# Generated by Django 4.2.10 on 2025-05-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0006_fincidentsbita_updated_at_alter_fincidentsbita_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DPremissas',
        ),
    ]
