# Generated by Django 4.2.10 on 2025-05-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0007_delete_dpremissas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPremissas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_incidents', models.IntegerField()),
                ('is_origem_correta', models.BooleanField()),
                ('is_categorias_operacionais_corretas', models.BooleanField()),
                ('is_categoria_resolucao_corretas', models.BooleanField()),
                ('is_tipo_ticket_correto', models.BooleanField()),
                ('is_tipo_indisponibilidade_correto', models.BooleanField()),
                ('is_fim_indisponibilidade_correto', models.BooleanField()),
                ('is_tempo_expurgo_correto', models.BooleanField()),
                ('is_em_espera_correto', models.BooleanField()),
                ('is_nota_resolucao_correto', models.BooleanField()),
                ('is_notas_ticket_correto', models.BooleanField()),
                ('is_id_antive_or_contrato_correto', models.BooleanField()),
                ('is_horas_lancadas', models.BooleanField()),
                ('is_cliente_notificado', models.BooleanField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_analytics.dassignmentgroup')),
            ],
            options={
                'db_table': 'd_premissas',
            },
        ),
    ]
