# Generated by Django 4.2.10 on 2025-05-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0008_dpremissas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpremissas',
            old_name='assignment',
            new_name='assignment_group',
        ),
    ]
