# Generated by Django 4.2.10 on 2025-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0009_rename_assignment_dpremissas_assignment_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpremissas',
            old_name='is_id_antive_or_contrato_correto',
            new_name='is_id_vantive_or_contrato_correto',
        ),
        migrations.AddField(
            model_name='dpremissas',
            name='is_sla_atendimento_no_prazo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
