# Generated by Django 4.2.10 on 2025-05-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0010_rename_is_id_antive_or_contrato_correto_dpremissas_is_id_vantive_or_contrato_correto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPremissa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_incidents', models.IntegerField(help_text='Quantidade de incidentes a serem sorteados')),
                ('meta_mensal', models.IntegerField(default=70, help_text='Meta mensal dos analistas em pontos')),
                ('assignment', models.OneToOneField(help_text='Assignment Group relacionado', on_delete=django.db.models.deletion.PROTECT, related_name='premissas', to='dw_analytics.dassignmentgroup')),
            ],
            options={
                'verbose_name': 'Premissa',
                'verbose_name_plural': 'Premissas',
                'db_table': 'd_premissa',
            },
        ),
        migrations.DeleteModel(
            name='DPremissas',
        ),
    ]
