# Generated by Django 4.2.10 on 2025-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0011_dpremissa_delete_dpremissas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIncidentSla',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=6, null=True)),
            ],
            options={
                'db_table': 'd_incident_sla',
            },
        ),
        migrations.AddField(
            model_name='dcompany',
            name='nome_correto',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='description',
            field=models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='dv_location',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='parent_incident',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='short_description',
            field=models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='u_data_normalizacao_servico',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='u_justificativa_isolamento',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='u_tempo_indisponivel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fincident',
            name='u_vendor_ticket',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fincidenttask',
            name='description',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True),
        ),
    ]
