# Generated by Django 4.2.10 on 2025-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblsolarinterfacesvgr',
            old_name='municÝpio',
            new_name='municipio',
        ),
    ]
