# Generated by Django 4.2.10 on 2025-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0002_rename_municýpio_tblsolarinterfacesvgr_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsolarinterfacesvgr',
            name='municipio',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MUNICÍPIO', max_length=255, null=True),
        ),
    ]
