# Generated by Django 4.2.10 on 2025-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0003_alter_tblsolarinterfacesvgr_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarIDVGRInterfaceCorrigido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('company_remedy', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Company_Remedy', max_length=255, null=True)),
                ('nome_do_cliente', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nome_do_cliente', max_length=255, null=True)),
                ('razao_social', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RAZAO_SOCIAL', max_length=255, null=True)),
                ('grupo_corporativo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GRUPO_CORPORATIVO', max_length=255, null=True)),
                ('id_vgr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ID_VGR', max_length=255, null=True)),
                ('designador', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DESIGNADOR', max_length=255, null=True)),
                ('operadora', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Operadora', max_length=255, null=True)),
                ('tecnologia', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tecnologia', max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MUNICÍPIO', max_length=255, null=True)),
                ('uf', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UF', max_length=255, null=True)),
                ('velocidade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VELOCIDADE', max_length=255, null=True)),
                ('status_vantive', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='STATUS_VANTIVE', max_length=255, null=True)),
                ('interfaceid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='INTERFACEID', max_length=255, null=True)),
                ('id_vantive_principal', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ID_VANTIVE_PRINCIPAL', max_length=255, null=True)),
                ('ip_interface', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IP_Interface', max_length=255, null=True)),
                ('ip_node', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IP_Node', max_length=255, null=True)),
                ('operadora2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OPERADORA2', max_length=255, null=True)),
                ('operadora3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OPERADORA3', max_length=255, null=True)),
            ],
            options={
                'db_table': 'solar_id_vgr_interface_corrigido',
            },
        ),
    ]
