# Generated by Django 4.2.10 on 2025-05-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0004_solaridvgrinterfacecorrigido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='company_remedy',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='company_remedy', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='designador',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='designador', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='grupo_corporativo',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='grupo_corporativo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='id_vantive_principal',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='id_vantive_principal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='id_vgr',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='id_vgr', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='interfaceid',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='interfaceid', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='ip_interface',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ip_interface', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='ip_node',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ip_node', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='municipio',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='municipio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='nome_do_cliente',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_do_cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='operadora',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='operadora', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='operadora2',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='operadora2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='operadora3',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='operadora3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='razao_social',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='razao_social', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='status_vantive',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='status_vantive', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='tecnologia',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tecnologia', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='uf',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='uf', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='velocidade',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Field', max_length=255, null=True),
        ),
    ]
