# Generated by Django 4.2.10 on 2025-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0005_alter_solaridvgrinterfacecorrigido_company_remedy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solaridvgrinterfacecorrigido',
            name='historico_ids',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='historico_ids', max_length=255, null=True),
        ),
    ]
