# Generated by Django 4.2.10 on 2025-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0006_solaridvgrinterfacecorrigido_historico_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='historico_ids',
            field=models.JSONField(db_column='historico_ids', default=list),
        ),
    ]
