# Generated by Django 4.2.10 on 2025-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0007_alter_solaridvgrinterfacecorrigido_historico_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solaridvgrinterfacecorrigido',
            name='velocidade',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='velocidade', max_length=255, null=True),
        ),
    ]
