# Generated by Django 4.2.10 on 2025-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0009_solarinterface_solarnomeclientecorreto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarInterfaceOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('company_remedy', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('grupo_corporativo', models.CharField(max_length=255)),
                ('id_vgr', models.CharField(max_length=255)),
                ('designador', models.CharField(max_length=255)),
                ('operadora', models.CharField(max_length=255)),
                ('nome_operadora', models.CharField(max_length=255)),
                ('nome_operadora_atual', models.CharField(max_length=255)),
                ('tecnologia', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('velocidade', models.CharField(max_length=255)),
                ('banda_contratada_entrada', models.CharField(max_length=255)),
                ('status_vantive', models.CharField(max_length=255)),
                ('interface_id', models.CharField(max_length=255)),
                ('ip_interface', models.CharField(max_length=255)),
                ('ip_node', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('interface_name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('nome_interface', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'solar_interface_original',
            },
        ),
    ]
