# Generated by Django 4.2.10 on 2025-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0010_solarinterfaceoriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarinterfaceoriginal',
            name='uf',
            field=models.CharField(max_length=255),
        ),
    ]
