# Generated by Django 4.2.10 on 2025-06-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0011_alter_solarinterfaceoriginal_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarNomeTecnologiaCorreto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_solar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_solar', max_length=255)),
                ('nome_correto', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_correto', max_length=255)),
            ],
            options={
                'db_table': 'solar_nome_tecnologia_correto',
            },
        ),
    ]
