# Generated by Django 4.2.10 on 2025-06-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0012_solarnometecnologiacorreto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarinterface',
            old_name='nome_do_cliente',
            new_name='nome_cliente',
        ),
    ]
