# Generated by Django 4.2.10 on 2025-06-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0013_rename_nome_do_cliente_solarinterface_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarinterface',
            name='nome_cliente',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_cliente', max_length=255, null=True),
        ),
    ]
