# Generated by Django 4.2.10 on 2025-06-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0014_alter_solarinterface_nome_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarinterfaceoriginal',
            old_name='municipio',
            new_name='cep',
        ),
        migrations.RemoveField(
            model_name='solarinterfaceoriginal',
            name='uf',
        ),
    ]
