# Generated by Django 4.2.10 on 2025-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0015_rename_municipio_solarinterfaceoriginal_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarNodeOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('company_remedy', models.CharField(max_length=255)),
                ('grupo_corporativo', models.CharField(max_length=255)),
                ('id_vgr', models.CharField(max_length=255)),
                ('designador', models.CharField(max_length=255)),
                ('operadora', models.CharField(max_length=255)),
                ('tecnologia', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ip_node', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'solar_node_original',
            },
        ),
    ]
