# Generated by Django 4.2.10 on 2025-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0016_solarnodeoriginal'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarnodeoriginal',
            name='status_vantive',
            field=models.CharField(default='nulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarnodeoriginal',
            name='velocidade',
            field=models.CharField(default='nulo', max_length=255),
            preserve_default=False,
        ),
    ]
