# Generated by Django 4.2.10 on 2025-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0017_solarnodeoriginal_status_vantive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarNode',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('company_remedy', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='company_remedy', max_length=255, null=True)),
                ('nome_cliente', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_cliente', max_length=255, null=True)),
                ('razao_social', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='razao_social', max_length=255, null=True)),
                ('grupo_corporativo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='grupo_corporativo', max_length=255, null=True)),
                ('id_vgr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='id_vgr', max_length=255, null=True)),
                ('designador', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='designador', max_length=255, null=True)),
                ('operadora', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='operadora', max_length=255, null=True)),
                ('tecnologia', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tecnologia', max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='municipio', max_length=255, null=True)),
                ('uf', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='uf', max_length=255, null=True)),
                ('velocidade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='velocidade', max_length=255, null=True)),
                ('status_vantive', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='status_vantive', max_length=255, null=True)),
                ('ip_node', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ip_node', max_length=255, null=True)),
                ('historico_ids', models.JSONField(db_column='historico_ids', default=list)),
            ],
            options={
                'db_table': 'solar_node',
            },
        ),
    ]
