# Generated by Django 4.2.10 on 2025-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0018_solarnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarnode',
            name='node_id',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='node_id', max_length=255, null=True),
        ),
    ]
