# Generated by Django 4.2.10 on 2025-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0019_solarnode_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarnomeclientecorreto',
            name='nome_solar',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_solar', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='solarnomeoperadoracorreto',
            name='nome_solar',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_solar', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='solarnometecnologiacorreto',
            name='nome_solar',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nome_solar', max_length=255, unique=True),
        ),
    ]
