# Generated by Django 4.2.10 on 2025-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bi', '0020_alter_solarnomeclientecorreto_nome_solar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarinterface',
            name='interface_id',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='interface_id', max_length=255, null=True),
        ),
    ]
