# Generated by Django 4.2.10 on 2025-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPollerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_poller_assignment_id', models.CharField(max_length=100, null=True)),
                ('node_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dim Custom Poller Assignment',
                'verbose_name_plural': 'Dim Custom Poller Assignments',
                'db_table': 'd_custom_poller_assignment',
            },
        ),
        migrations.CreateModel(
            name='CustomPollerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_poller_assignment_id', models.CharField(max_length=100, null=True)),
                ('node_id', models.CharField(max_length=100, null=True)),
                ('row_id', models.CharField(max_length=100, null=True)),
                ('date_time', models.CharField(max_length=100, null=True)),
                ('raw_status', models.CharField(max_length=255, null=True)),
                ('weight', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fato Custom Poller Statistics',
                'verbose_name_plural': 'Fato Custom Poller Statistics',
                'db_table': 'f_custom_poller_statistics',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, null=True)),
                ('interface_id', models.CharField(max_length=100, null=True)),
                ('interface_name', models.CharField(max_length=255, null=True)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('id_vgr', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dim Interface (Capacity)',
                'verbose_name_plural': 'Dim Interfaces (Capacity)',
                'db_table': 'd_interface',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_cliente', models.CharField(max_length=255, null=True)),
                ('node_id', models.CharField(max_length=10, null=True)),
                ('id_vgr', models.CharField(max_length=7, null=True)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('automatizacao', models.CharField(max_length=20, null=True)),
                ('redundancia', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Dim Node (Capacity)',
                'verbose_name_plural': 'Dim Nodes (Capacity)',
                'db_table': 'd_node',
            },
        ),
        migrations.CreateModel(
            name='ResponseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, null=True)),
                ('date_time', models.CharField(max_length=100, null=True)),
                ('avg_response_time', models.CharField(max_length=100, null=True)),
                ('percent_loss', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fato Response Time (Capacity)',
                'verbose_name_plural': 'Fato Response Times (Capacity)',
                'db_table': 'f_response_time',
            },
        ),
    ]
