# Generated by Django 4.2.10 on 2025-08-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='automatizacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
