# Generated by Django 4.2.10 on 2025-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0002_alter_node_automatizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompollerstatistics',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='responsetime',
            name='date_time',
        ),
        migrations.AddField(
            model_name='custompollerassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custompollerassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='custompollerassignment',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custompollerstatistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custompollerstatistics',
            name='date',
            field=models.DateField(default='2025-08-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custompollerstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='custompollerstatistics',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='responsetime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='responsetime',
            name='date',
            field=models.DateField(default='2025-08-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsetime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='responsetime',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
