# Generated by Django 4.2.10 on 2025-08-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0003_remove_custompollerstatistics_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompollerstatistics',
            name='node_id',
        ),
    ]
