# Generated by Django 4.2.10 on 2025-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0004_remove_custompollerstatistics_node_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompollerstatistics',
            name='custom_poller_assignment_id',
        ),
        migrations.AddField(
            model_name='custompollerstatistics',
            name='node_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='custompollerstatistics',
            name='raw_status',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='custompollerstatistics',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
