# Generated by Django 4.2.10 on 2025-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0005_remove_custompollerstatistics_custom_poller_assignment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('log', models.JSONField()),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'db_table': 'task_log',
            },
        ),
    ]
