# Generated by Django 4.2.10 on 2025-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0006_tasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('node_id', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('in_average_bps', models.FloatField(null=True)),
                ('out_average_bps', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Fato Interface Traffic (Capacity)',
                'verbose_name_plural': 'Fato Interface Traffics (Capacity)',
                'db_table': 'f_interface_traffic',
            },
        ),
    ]
