# Generated by Django 4.2.10 on 2025-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0007_interfacetraffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('classificacao', models.CharField(choices=[('Bom', 'Bom'), ('Ótimo', 'Ótimo'), ('Ruim', 'Ruim')], max_length=10)),
                ('criterio', models.CharField(choices=[('Jitter', 'Jitter'), ('Latência', 'Latência'), ('Perda de Pacote', 'Perda de Pacote')], max_length=20)),
                ('faixa_min', models.FloatField()),
                ('faixa_max', models.FloatField(blank=True, null=True)),
                ('nota', models.PositiveSmallIntegerField()),
                ('regiao', models.CharField(choices=[('Capital', 'Capital'), ('Interior', 'Interior')], max_length=10)),
                ('tecnologia', models.CharField(choices=[('Banda Larga Fixa', 'Banda Larga Fixa'), ('IP Dedicado', 'IP Dedicado'), ('MPLS', 'MPLS'), ('Banda Larga Móvel', 'Banda Larga Móvel'), ('Banda Larga Satélite', 'Banda Larga Satélite')], max_length=30)),
                ('tipo_peso', models.CharField(choices=[('Flat', 'Peso Flat'), ('Threshold', 'Peso por Threshold')], max_length=10)),
            ],
            options={
                'verbose_name': 'Avaliação Técnica',
                'verbose_name_plural': 'Avaliações Técnicas',
                'db_table': 'd_avaliacao_tecnica',
                'ordering': ['tecnologia', 'regiao', 'criterio', 'classificacao'],
            },
        ),
    ]
