# Generated by Django 4.2.10 on 2025-09-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0008_avaliacaotecnica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaotecnica',
            name='tipo_peso',
        ),
    ]
