# Generated by Django 4.2.10 on 2025-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0009_remove_avaliacaotecnica_tipo_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
