# Generated by Django 4.2.10 on 2025-09-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0010_node_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='tecnologia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
