# Generated by Django 4.2.10 on 2025-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0011_node_tecnologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='servico',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
