# Generated by Django 4.2.10 on 2025-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_datacenter', '0012_interface_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='servico',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
