# Generated by Django 4.2.10 on 2025-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
